# Nginx setup
FROM nginx:1.21.1-alpine AS prod-stage
# Copy static files from client-build
# COPY --from=client-build /app/client/dist /usr/share/nginx/html
COPY ./client/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]