version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    container_name: LibreChat
    labels:
      - "com.librechat.description=Libre-Prod Api"    
    ports:
      - 3080:3080
    depends_on:
      - mongodb
    restart: always
    extra_hosts:
    - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
    volumes:
      - ./images:/app/client/public/images
      - ./librechat.yaml:/app/librechat.yaml
  # client:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.multi
  #     target: client-build
  #   container_name: LibreChat-Client
  #   labels:
  #     - "com.librechat.description=Libre-Prod Client"     
  #   ports:
  #     - 80:80
  #     # - 443:443
  #   depends_on:
  #     - api
  #   restart: always
  #   env_file:
  #     - .env    
      # stdin_open: true
      # tty: true

  nginx:
    image: nginx:1.21.1-alpine
    container_name: LibreChat-Nginx
    labels:
      - "com.librechat.description=Libre-Prod Nginx"       
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
    ports:
    - 80:80  # Changed from 80 to 8080 to avoid conflicts on the host
    - 443:443  # Changed from 443 to 8443 if needed
    depends_on:
      - api
    restart: always
    command: [nginx-debug, '-g', 'daemon off;']



  mongodb:
    container_name: chat-mongodb
    # ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
    #   - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.0
    # ports: # Uncomment this to access meilisearch from outside docker
    #   - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data:/meili_data
